# Generated by Django 5.0.3 on 2026-06-25 11:03

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(help_text='Delimitación geográfica exterior del campus (WGS84)', srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Campuses',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Código identificador del edificio (ej: EPS-I)', max_length=10, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(help_text='Huella perimetral del edificio (WGS84)', srid=4326)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='maps.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(help_text='Número de planta (0=Baja, 1=Primera, -1=Sótano)')),
                ('name', models.CharField(help_text='Nombre de la planta (ej: Planta Primera)', max_length=50)),
                ('altitude', models.FloatField(default=0.0, help_text='Altitud relativa en metros desde el suelo')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(help_text='Contorno geométrico de la planta', srid=4326)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='maps.building')),
            ],
            options={
                'ordering': ['level'],
                'unique_together': {('building', 'level')},
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, help_text='ID del espacio en planos externos', max_length=100, null=True)),
                ('name', models.CharField(help_text='Ej: Aula 1.1, Despacho 202', max_length=100)),
                ('space_type', models.CharField(choices=[('ROOM', 'Aula / Despacho'), ('CORRIDOR', 'Pasillo / Zona de Circulación'), ('STAIRS', 'Escaleras'), ('ELEVATOR', 'Ascensor'), ('RESTROOM', 'Servicios / Aseos'), ('RESTRICTED', 'Zona Restringida / Técnica')], default='ROOM', max_length=20)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(help_text='Geometría del espacio interior (WGS84)', srid=4326)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='maps.floor')),
            ],
        ),
    ]
