# Generated by Django 5.1.15 on 2026-06-27 18:01

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nombre opcional de la conexión (ej: Pasillo-Aula101)', max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('is_accessible', models.BooleanField(default=True, help_text='Indica si este tramo es apto para personas con movilidad reducida (sin escaleras)')),
                ('source_space', models.ForeignKey(help_text='Espacio de origen (Nodo A)', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='maps.space')),
                ('target_space', models.ForeignKey(help_text='Espacio de destino (Nodo B)', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='maps.space')),
            ],
        ),
    ]
