# Generated by Django 5.1.15 on 2026-07-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_navigationedge'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID del edificio en planos externos', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID del campus en planos externos', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='floor',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID de la planta en planos externos', max_length=100, null=True),
        ),
    ]
