# Generated by Django 5.1.15 on 2026-07-07 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('maps', '0003_building_external_id_campus_external_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(help_text='Archivo de imagen del plano (PNG/JPG/SVG)', upload_to='spatial_plans/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('UPLOADED', 'Cargado / Pendiente'), ('PREPROCESSING', 'Preprocesando Imagen'), ('EXTRACTING', 'Extrayendo con IA'), ('REQUIRES_REVIEW', 'Requiere Revisión Manual'), ('PROCESSED', 'Procesado Completamente'), ('FAILED', 'Error en el Pipeline')], db_index=True, default='UPLOADED', max_length=20)),
                ('file_hash', models.CharField(help_text='Hash SHA-256 del archivo', max_length=64, unique=True)),
                ('intermediate_proposal', models.JSONField(blank=True, help_text='Esquema JSON normalizado de la propuesta', null=True)),
                ('ai_metadata', models.JSONField(blank=True, default=dict, help_text='Métricas de ejecución: {prompt, tokens_used, cost_usd, provider_name}')),
                ('error_log', models.TextField(blank=True, help_text='Traza detallada del error si el estado es FAILED', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
