# Generated by Django 5.1.15 on 2026-08-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_spatialplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spatialplan',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Cargado / Pendiente'), ('PREPROCESSING', 'Preprocesando Imagen'), ('EXTRACTING', 'Extrayendo con IA'), ('REQUIRES_REVIEW', 'Requiere Revisión Manual'), ('PROCESSED', 'Procesado Completamente'), ('APPROVED', 'Aprobado y Persistido'), ('REJECTED', 'Rechazado por el Revisor'), ('FAILED', 'Error en el Pipeline')], db_index=True, default='UPLOADED', max_length=20),
        ),
    ]
